### ISSUE TITLE
CSS3 Selector

### ISSUE THREAD

**Issue by isChenKan** [isChenKan/blog#2]
最近在做一些JavaScript的东西，没什么时间写总结，昨天逛Stack Overflow的时候看到别人的代码用了display: flex;来布局。interesting…找到了阮一峰老师写的flex布局的博客来看，flex的事情以后再说，先说说中间发现的一个意思的东西：

p:nth-child()和p:nth-of-type();
---
这两个选择器还是第一次见，前段时间学CSS的时候根本没有注意到这些选择器，当时只记得一些基本的选择器还有一些伪选择器。比较偏的也就知道first-child和last-child了。于是就Google了一下，具体介绍看：[CSS3: nth-child() Selector](https://www.w3schools.com/cssref/sel_nth-child.asp) 基础的我就不啰嗦了，来谈谈这两个选择器的区别。

假如有这样一个HTML代码：
```html
<section>
    <p>chen</p>
    <p>kan</p>
</section>
```
如果我们想要第二段里面的内容变成蓝色，你可以这样：
```css
p:nth-child(2) {color: #0000ff;}
```
当然你也可以这样：
```css
<section>
    <h1>Still works?</h1>
    <p>chen</p>
    <p>kan</p>
</section>
```
这时候当你使用：
```css
p:nth-child(2) {color: #0000ff;}
```
会意外的把第一段里面的文字”chen”变成蓝色，而不是第二段中的”kan”。因为这时候section的第二个子元素是`<p>chen</p>`。但使用下面这段代码可以达到目的：
```css
p:nth-of-type(2) {color: #0000ff;}
```
因为它指定选择第二个`<p>`元素。这是选中的便是第二个段落。当下面这种情况出现时：
```html
<section>
    <h1>Still works?</h1>
    <h1>does't work</h1>
    <p>chen</p>
    <p>kan</p>
</section>
```
当你使用：
```css
p:nth-child(2) {color: #0000ff;}
```
它甚至什么都不会选到了，因为第二个子元素不是`<p>`。但是使用nth-of-type()还是可以选中第二段文字。所以用nth-of-type()可能是更好的选择。

另外这两个选择器括号里面不仅只有数字而已，还有一些有趣的选择可以让它们更加灵活，比如可以使用odd和even，这两个分别代表单双数，可以交叉选择。还可以使用表达式等等，具体参考：[CSS3: nth-of-type() Selector](https://www.w3schools.com/cssref/sel_nth-of-type.asp)。

element1 ~ element2
---
 这个选择器是css3的，intro:
>p ~ ul {background: #fff;} 
>Set a background color for all \<ul\> elements that are preceded by a \<p\> element with the same parent.

他们要有相同的父元素，也就是他们是同级元素，另外，他可以和其他选择区组合使用。

enjoy:smile:
