### ISSUE TITLE
Two kinds of CSS carousel

### ISSUE THREAD

**Issue by isChenKan** [isChenKan/blog#5]
只用CSS的轮播图：
---
首先你需要把这几张图排列成一个类似于圆圈的形状，那么就需要：
```css
transfrom: rotateY(-deg) translateZ(-px);
```
具体的数据则根据你的图片数量而定，比如有6张图，那就是 360 / 6 = 60deg，也就是rotateY(60deg)了。
translateZ则是为了不让他们都挤到一块儿，都向外移动，移动多少取决于图片的尺寸。

transform-style: preserve-3d;
---
这个属性很重要，有点难记。如果没写这个属性在container里面的话，就无法看到3d轮播的效果。

@keyframes {}
---
可以按从0%写到100%，可以使用rotateX()和rotateY()来配合实现很酷炫的3D效果。
```css
@keyframes rotate-frame {
        0% {
            transform: rotateX(-20deg) rotateY(0deg);
        }
        10% {
            transform: rotateX(-20deg) rotateY(36deg);
        }
        20% {
            transform: rotateX(-20deg) rotateY(72deg);
        }
        30% {
            transform: rotateX(-20deg) rotateY(108deg);
        }
        40% {
            transform: rotateX(-20deg) rotateY(144deg);
        }
        50% {
            transform: rotateX(-20deg) rotateY(180deg);
        }
        60% {
            transform: rotateX(-20deg) rotateY(216deg);
        }
        70% {
            transform: rotateX(-20deg) rotateY(252deg);
        }
        80% {
            transform: rotateX(-20deg) rotateY(288deg);
        }
        90% {
            transform: rotateX(-20deg) rotateY(324deg);
        }
        100% {
            transform: rotateX(-20deg) rotateY(360deg);
        }
```
这是个一个很普通的旋转transition效果。

2.Make an image carousel with only CSS
---
如果想做一个点击两边的箭头来切换轮播图图片的效果，而又不能使用JavaScript的话，用纯css也是可以实现的，只不过可控性没有js写的好，用css的话主要是用\<label for="#"\>标签和\<input type="radio"\>，由于input标签的单选按钮正好跟轮播图的性质契合，所以可以将左右箭头绑定到单选按钮上，因为\<label\>的for可以绑定input元素的ID，从而实现点击label就可以实现切换图片的效果， 这样就可以点击按钮实现图片的切换了。大致思路是这样的。关键代码：
```html
    <div class="group">
      <input type="radio" name="test" id="0" value="0">
      <label for="2" class="previous"><</label>
      <label for="1" class="next">></label>
      <div class="content">
        <img src="#">
      </div>
    </div>
    <div class="group">
      <input type="radio" name="test" id="1" value="1">
      <label for="0" class="previous"><</label>
      <label for="2" class="next">></label>
      <div class="content">
        <img src="#">
      </div>
    </div>
    <div class="group">
      <input type="radio" name="test" id="2" value="2">
      <label for="1" class="previous"><</label>
      <label for="0" class="next">></label>
      <div class="content">
        <img src="#">
      </div>
    </div>
```
CSS关键部分：
```css
  .group input:checked ~ .content {
    display: block;
  }
  .group input:checked ~ .previous,
  .group input:checked ~ .next {
    display: block;
  }
```
enjoy:smile:
