### ISSUE TITLE
CSS Variables & CSSStyleDeclaration.setProperty()

### ISSUE THREAD

**Issue by isChenKan** [isChenKan/blog#7]
1.CSS Variables
---
有时候当我们需要在CSS中重复的使用一个属性的时候，比如颜色值，这样会导致程序的维护性很差，因为当我们需要修改这个属性的值的时候就需要修改很多的地方。这时候就出现了一种叫做CSS变量的东西。

声明：
```css
:root {      // Selects the document's root element
  --main-color: #337ab7;
}
```
使用的时候请用var()函数：
```css
p {
  background: var(--main-color);
}
```
有点像其他语言中的全局变量这么个意思。

2.CSSStyleDeclaration.setProperty()
---
用setProperty()在JavaScript中设置CSS的style的属性值，使用语法：
```javascript
document.documentElement.style.setProperty('margin', '1px 2px');
```

enjoy:smile:
